config/routes.rb
Rails.application.routes.draw do
  get 'home/about', to: 'homes#about'
  devise_for :users

  root to: 'homes#top'
  resources :books, only: [:new, :index, :show, :create, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only:[:create, :destroy]
  end
  
  resources :users, only: [:index, :show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :title, presence: true
  validates :body, presence: true
  validates :body,    length: { maximum: 200 }

end

app/models/book_comment.rb
class BookComment < ApplicationRecord

  validates :comment, presence: true

  belongs_to :user
  belongs_to :book
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :book
  
  validates_uniqueness_of :book_id, scope: :user_id
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  attachment :profile_image

  validates :name, uniqueness: true
  validates :name,    length: { in: 2..20 }
  validates :introduction,    length: { maximum:50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top, :about]
    
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  
  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
    redirect_to book_path(book)
  end

  def destroy
    book = Book.find(params[:book_id])
    BookComment.find_by(id: params[:id]).destroy
    redirect_to book_path(book)
  end
  
  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :baria_user, only: [:edit, :destroy, :update]


  def new
    @book = Book.new
  end

  def index
    @user = current_user
    @books = Book.all
    @book = Book.new
  end

  def create
    @user = current_user
    @books = Book.all
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: 'Book was successfully created!'
    else
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def show
    @booknew = Book.new
    @book = Book.find(params[:id])
    @user = User.find(@book.user_id)
    @book_comment = BookComment.new
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id), notice: 'Book was successfully updated!'
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end


  private

  def book_params
    params.require(:book).permit(:title, :body)

  end

  def baria_user
    unless Book.find(params[:id]).user.id.to_i == current_user.id
      redirect_to books_path
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_to request.referer
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_to request.referer
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
  end

  def about
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_current_user, {only: [:edit, :update]}
  def ensure_current_user
    if current_user.id == params[:id].to_i
    else
      redirect_to user_path(current_user)
    end
  end
  
  def index
    @booknew = Book.new
    @users = User.all
    @user = current_user
  end

  def show
    @book = Book.new
    @user = User.find(params[:id])
    @books = @user.books
    @book_comment = BookComment.new

  end
  def edit
    @user = User.find(params[:id])
  end

  def update
    # @user = User.find(params[:id])
    @user = current_user
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: 'User was successfully updated!'
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/book_helper.rb
module BookHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<div class="p-3">
  <div>
    <h1>User info</h1></br>
    <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image_user.jpg" %>
  </div>
  <div class="border-top" style="padding:10px;">
    <strong>name</strong>
    <strong> <%= user.name %></strong>
  </div>
  <div class="border-top" style="padding:10px;">
    <strong></strong>introduction</strong>
    <strong> <%= user.introduction %></strong>
  </div>
</div>

  <%= link_to edit_user_path(user.id), class: 'btn w-100 btn-secondary' do %>
    <i class="fas fa-user-cog"></i>
  <% end %>
  

<div class="p-3">
  <h1>New book</h1>
  <%= form_with model: book, url: books_path, local:true do |f| %>
    <div class="field">
      <p>Title</p>
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <p>Opinion</p>
      <%= f.text_area :body %></br>
    </div>
    <div class="actions">
      <input type="submit" name="commit" value="Create Book" class="btn btn-success" data-disable-with="Create Book">
    </div>
  <% end %>
</div>
</div>

app/views/books/edit.html.erb
<% if @book.errors.any? %>
  <div class="m-2 text-danger">
    <%= @book.errors.count %>errors have occurred.
    <% @book.errors.full_messages.each do |message| %>
  </div>
    <li class="m-2 text-danger"><%= message %></li>
  <% end %>
<% end %>
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>Editing Book</h1>
      <%= form_with model:@book, local: true do |f| %>
      <div class="field">
        <h4>Title</h4>
        <%= f.text_field :title %>
      </div>
      <div class="field">
        <h4>Opinion</h4>
        <%= f.text_area :body %></br>
      <div class="field">
        <input type="submit" name="commit" value="Update Book" class="btn btn-success" data-disable-with="Update Book">
      </div>
      <% end %>
      
      
      <%= link_to "Show", book_path(@book) %>
      |
      <%= link_to "Back", books_path %>
        
    </div>
  </div>
</div>
<main>

app/views/books/index.html.erb
<% if @book.errors.any? %>
  <div class="m-2 text-danger">
    <%= @book.errors.count %>errors have occurred.
    <% @book.errors.full_messages.each do |message| %>
  </div>
    <li class="m-2 text-danger"><%= message %></li>
  <% end %>
<% end %>
<main>
  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <%= render 'books/list', book: @book, user: @user %>
      <div class="col-md-8 offset-md-1">
        <h1>Books</h1>
        <table class="table">
          <thead>
            <tr>
              <th colspan="1"></th>
              <th>Title</th>
              <th>Opinion</th>
            </tr>
          </thead>
          <tbody>
            <% @books.each do |book| %>
              <tr>
                <td>
                  <%= link_to user_path(book.user_id) do %>
                    <%= attachment_image_tag book.user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image_user.jpg" %>
                  <% end %>
                </td>
                <td><%= link_to book.title, book_path(book.id) %></td>
                <td><%= book.body %></td>
                <% if book.favorited_by?(current_user) %>
                  <p>
                    <td>
                      <%= link_to book_favorites_path(book), method: :delete do %>
                        <p class="text-danger">
                          <i class="fas fa-heart"></i><%= book.favorites.count %>
                        </p>
                      <% end %>
                    </td>
                  </p>
                  <% else %>
                  <p>
                    <td>
                      <%= link_to book_favorites_path(book), method: :post do %>
                        <p class="text-primary">
                          <i class="fas fa-heart"></i><%= book.favorites.count %>
                        </p>
                      <% end %>
                    </td>
                  </p>
                <% end %>
                <td><%= "コメント数：#{book.book_comments.count}" %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/books/new.html.erb
<h1>New book</h1>
<%= form_with model: @book, local:true do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Opinion</h4>
  <%= f.text_area :body %>
  <%= f.submit '投稿' %>
<% end %>

app/views/books/show.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <%= render 'books/list', book: @booknew, user: @user %>
      <div class="col-md-8 offset-md-1">
        <h1>Book detail</h1>
        <table class="table">
          <tbody>
              <tr>
                <td>
                  <%= attachment_image_tag @book.user, :profile_image, :fill, 50, 50, format: 'jpeg', fallback: "no_image_user.jpg" %></br>
                  <%= link_to  @book.user.name, user_path(@book.user_id) %>
                </td>
                <td><%= link_to  @book.title, book_path(@book) %></td>
                <td><%= @book.body %></td>
                <% if @book.user == current_user %>
                  <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-success" %></td>
                  <td><%= link_to "Destroy", book_path(@book), class: "btn btn-danger", method: :delete, data: { confirm: "Are you sure?"} %></td>
                <% end %>
                <% if @book.favorited_by?(current_user) %>
                  <p>
                    <td>
                      <%= link_to book_favorites_path(@book), method: :delete do %>
                        <p class="text-danger">
                          <i class="fas fa-heart"></i><%= @book.favorites.count %>
                        </p>
                      <% end %>
                    </td>
                  </p>
                  <% else %>
                  <p>
                    <td>
                      <%= link_to book_favorites_path(@book), method: :post do %>
                        <p class="text-primary">
                          <i class="fas fa-heart"></i><%= @book.favorites.count %>
                        </p>
                      <% end %>
                    </td>
                  </p>
                <% end %>
                <td><p>コメント数：<%= @book.book_comments.count %></p></td>
              </tr>
          </tbody>
        </table>
        <table class="table">
          <tbody>
              <tr>
                <td>
                <% @book.book_comments.each do |book_comment| %>
                  <%= attachment_image_tag @book.user, :profile_image, :fill, 50, 50, format: 'jpeg', fallback: "no_image_user.jpg" %></br>
                  <%= link_to  book_comment.user.name, user_path(book_comment.user_id) %>
                </td>
                <td><%= book_comment.comment %></td>
                <% if book_comment.user == current_user %>
                  <td><%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), class: "btn btn-danger", method: :delete %></td>
                <% end %>
                <% end %>
                </td>
              </tr>
          </tbody>
        </table>
        <div>
          <%= form_with(model:[@book, @book_comment], local: true) do |f| %>
            <%= f.text_area :comment, size: "80x10" %></br>
            <%= f.submit "送信" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/homes/about.html.erb
<h1 class="text-center">Welcome to <i class="fas fa-book"></i><strong>Bookers!</strong></h1>

app/views/homes/top.html.erb
<main class="center-block">
  <div class="container">
    <div class="row">
      <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
          <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
          <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
          <p>you can share and exchange  your opinions , inpressions , and emotions</p>
          <p> about various books!</p>
          <div class="btn-wrapper col-10 mx-auto">
            <div class="row">
              <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
            </div>
            <div class="row">
              <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign Up</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/204ded6ce9.js" crossorigin="anonymous"></script>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="bg-dark text-white">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <% if user_signed_in? %>
            <a class="nav-link text-light" href="/book/index"><h3>Bookers</h3></a>
          <% else %>
            <a class="nav-link text-light" href="/"><h3>Bookers</h3></a>
          <% end %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
              <%= link_to ' Home', user_path(current_user.id), class: 'fas fa-home nav-link text-white' %>
              <%= link_to ' Users', users_path, class: 'fas fa-users nav-link text-white' %>
              <%= link_to ' Books', books_path, class: 'fas fa-book-open nav-link text-white' %>
              <%= link_to ' logout', destroy_user_session_path, method: :delete, class: 'fas fa-sign-out-alt nav-link text-white' %>
            <% else %>
              <%= link_to ' Home', root_path, class: 'fas fa-home nav-link text-white' %>
              <%= link_to ' About', home_about_path, class: 'fas fa-link nav-link text-white' %>
              <%= link_to " sign up", new_user_registration_path, class: 'fas fa-user-plus nav-link text-white' %>
              <%= link_to " login", new_user_session_path, class: 'fas fa-sign-in-alt nav-link text-white' %>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main class="mb-auto">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "#{key}") %>
      <% end %>
      <%= yield %>
    </main>
    <footer class="bg-white text-dark pt-5 pb-4">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <p class="text-center">CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>

    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <div class="m-2 text-danger">
    <%= @user.errors.count %>errors have occurred.
    <% @user.errors.full_messages.each do |message| %>
  </div>
    <li class="m-2 text-danger"><%= message %></li>
  <% end %>
<% end %>
<div class="container">
  <div class="row">
    <div class=class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>User info</h1>
        <%= form_with model:@user, local:true do |f| %>
        <div class="field">
          <label for="inputName">Name</label></br>
          <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"name"%></br>
        </div>
        <div class="field">
          <label for="inputImage">Image</label></br>
          <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %></br>
        </div>
        <div class="field">
          <label for="inputIntroduction">Introduction</label></br>
          <%= f.text_area :introduction, autofocus: true, id:"inputIntroduction", placeholder:"introduction"%></br>
        </div>
          <div class="form-group"></br>
            <input type="submit" name="commit" value="Update User" class="btn btn-secondary" data-disable-with="Update User"></br>
          </div>
        <% end %>
        
    </div>
  </div>
</div>
<main>
  

app/views/users/index.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <%= render 'books/list', book: @booknew, user: @user %>
      <div class="col-md-8 offset-md-1">
        <h1>Books</h1>
        <table class="table">
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
              <tr>
                <td><%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image_user.jpg" %></td>
                <td><%= user.name %></td>
                <td></td>
                <td><%= link_to 'Show', user_path(user.id) %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <%= render 'books/list', book: @book, user: @user %>
      <div class="col-md-8 offset-md-1">
        <h1>Books</h1>
        <table class="table">
          <thead>
            <tr>
              <th colspan="1"></th>
              <th>Title</th>
              <th>Opinion</th>
            </tr>
          </thead>
          <tbody>
            <% @books.each do |book| %>
              <tr>
                <td>
                  <%= link_to user_path(book.user_id) do %>
                    <%= attachment_image_tag book.user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image_user.jpg" %>
                  <% end %>
                </td>
                <td><%= link_to book.title, book_path(book) %></td>
                <td><%= book.body %></td>
                <% if book.favorited_by?(current_user) %>
                  <p>
                    <td>
                      <%= link_to book_favorites_path(book), method: :delete do %>
                        <p class="text-danger">
                          <i class="fas fa-heart"></i><%= book.favorites.count %>
                        </p>
                      <% end %>
                    </td>
                  </p>
                  <% else %>
                  <p>
                    <td>
                      <%= link_to book_favorites_path(book), method: :post do %>
                        <p class="text-primary">
                          <i class="fas fa-heart"></i><%= book.favorites.count %>
                        </p>
                      <% end %>
                    </td>
                  </p>
                <% end %>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>